### ISSUE TITLE
兄弟iOS集成tun2socks成功了吗？

### ISSUE THREAD

**Issue by iineva** [Tai7sy/v2ray_mobile_lib#3]
我运行http代理可以访问了，未成功集成tun2socks，内存占用浮动在12～14+之间，用一段时间就挂

另外直接使用v2ray官方提供的dat文件内存占用过大，使用国内IP规则直接启动内存占用过大启动失败，我的解决办法是根据官方的数据库生成代码，过滤只剩下cn的IP，导出更小的文件：https://github.com/v2ray/geoip

这是我导出的数据：
[geoip.dat.zip](https://github.com/Tai7sy/v2ray_mobile_lib/files/4337064/geoip.dat.zip)
[geosite.dat.zip](https://github.com/Tai7sy/v2ray_mobile_lib/files/4337065/geosite.dat.zip)

**Comment by Tai7sy** [comment]
geosite也太大, 只留geoip.dat保留CN, 另外v2ray-core需要大量阉割代码

**Comment by Tai7sy** [comment]
tun2socks还会占1M左右, 运行起来不能保证内存小于10M的话用一会总会炸.....
只能说一句傻逼苹果了

**Comment by iineva** [comment]
苹果确实煞笔，如果内存限制在20M，就好弄很多了
我看了一下socks5协议，客户端比较简单，现在的思路是想自己解析IP包，转成TCP/UDP流，将数据流发送到socks5端口，这样应该能省下一些内存

**Comment by iineva** [comment]
下午用这个包集成了tun2socks
https://github.com/eycorsican/go-tun2socks-mobile

**Comment by Tai7sy** [comment]
这个go语言版本, 占内存会更多吧

**Comment by iineva** [comment]
实测内存占用跟不集成这个差不多，不过也是也是容易挂
里面看到了很多c版本的tun2socks代码，没仔细看，估计核心逻辑是直接调用

**Comment by iineva** [comment]
与v2ray调用到的包应该很多重合的，打包出来静态库没变大多少，都是75M左右，我用的v2ray是main加载的所有包，未做精简

**Comment by Tai7sy** [comment]
直接拿着pototso代码, 删掉ss和一堆乱七八糟的删掉换成这个项目库可以直接用, 然后剩下的就是阉割功能
我现在打包出来60M , 加载路由规则多一点都会崩

**Comment by iineva** [comment]
有个问题不知道你有没有遇到，我测试过UDP和TCP包都能走代理了，YouTube可以正常看视频，但是不知道为什么下面老是弹出“无网络连接”，不知道是不是因为没开启DNS服务

**Comment by iineva** [comment]
我这边是UI只是自己做了简单的START按钮启动，然后先从粘贴板读取配置启动golang的核心库，没引入任何别的东西，打包出来18.5M

**Comment by Tai7sy** [comment]
静态库18M吗.....

**Comment by iineva** [comment]
.app文件夹未压缩18M，静态库75M

**Comment by Tai7sy** [comment]
他这个内存是PacketTunnel进程内存限制, app的UI随便搞没关系的啊- -

**Comment by iineva** [comment]
精简后不用规则能长时间稳定运行吗

**Comment by Tai7sy** [comment]
应该可以, 没有试过长时间链接, 但是要开启mux限制连接数

**Comment by empire-lfang** [comment]
> 苹果确实煞笔，如果内存限制在20M，就好弄很多了 我看了一下socks5协议，客户端比较简单，现在的思路是想自己解析IP包，转成TCP/UDP流，将数据流发送到socks5端口，这样应该能省下一些内存

您好,有demo可以参考下吗
