### ISSUE TITLE
go-bindata: No such file or directory

### ISSUE THREAD

**Issue by GL-Wen** [Tai7sy/v2ray_mobile_lib#5]
➜  v2ray_mobile_lib make init_env
rm -rf build
go get -d ./...
go get golang.org/x/mobile/cmd/gomobile
go: found golang.org/x/mobile/cmd/gomobile in golang.org/x/mobile v0.0.0-20200629153529-33b80540585f
gomobile init
# go get -u github.com/golang/protobuf/protoc-gen-go
cd tun2socksBinarys; /Applications/Xcode.app/Contents/Developer/usr/bin/make binarys
go get -u github.com/kevinburke/go-bindata/...
go-bindata -nometadata -nomemcopy -pkg tun2socksBinarys -o ./binary_386.go -tags 386 ArchIndep/ ArchDep/386/
make[1]: go-bindata: No such file or directory
make[1]: *** [tun2socksBinary.386] Error 1
make: *** [tun2socksBinaryDeps] Error 2

你好，请教一下这个错误怎么解决？

**Comment by Tai7sy** [comment]
go-bindata可能没装上 自己检查网络

**Comment by GL-Wen** [comment]
> go-bindata可能没装上 自己检查网络

命令行安装的go-bindata有问题，使用brew安装一切正常
现在研究一下iOS该如何接入😊
