### ISSUE TITLE
There are some errors when i exec make build_ios command . Could you give some help ?

### ISSUE THREAD

**Issue by fuqiangleon** [Tai7sy/v2ray_mobile_lib#8]
$ make build_ios

mkdir -p build
gomobile bind -a -ldflags "-s -w" -tags ios -target=ios -o build/libv2ray.framework github.com/Tai7sy/v2ray_mobile_lib
gomobile: darwin-arm64: go build -tags ios ios -ldflags -s -w -buildmode=c-archive -o /var/folders/9t/nn0pycbd1397xxfxvql9b3hr0000gn/T/gomobile-work-150681088/libv2ray-arm64.a ./gobind failed: exit status 2
# github.com/Tai7sy/v2ray_mobile_lib
/Users/hugo/Downloads/v2ray_mobile_lib-master/interact.go:162:25: cannot use config (type *"github.com/v2fly/v2ray-core/v4".Config) as type *"v2ray.com/core".Config in argument to "v2ray.com/core".New
/Users/hugo/Downloads/v2ray_mobile_lib-master/interact.go:234:3: cannot use func literal (type func("v2ray.com/core/app/log".LogType, "v2ray.com/core/app/log".HandlerCreatorOptions) ("v2ray.com/core/common/log".Handler, error)) as type "v2ray.com/core/app/log".HandlerCreator in argument to "v2ray.com/core/app/log".RegisterHandlerCreator
/Users/hugo/Downloads/v2ray_mobile_lib-master/interact.go:248:46: cannot use point.dialer (type *VPN.ProtectedDialer) as type "v2ray.com/core/transport/internet".SystemDialer in argument to "v2ray.com/core/transport/internet".UseAlternativeSystemDialer:
	*VPN.ProtectedDialer does not implement "v2ray.com/core/transport/internet".SystemDialer (wrong type for Dial method)
		have Dial(context.Context, "v2ray.com/core/common/net".Address, "v2ray.com/core/common/net".Destination, *"v2ray.com/core/transport/internet".SocketConfig) ("net".Conn, error)
		want Dial(context.Context, "github.com/v2fly/v2ray-core/v4/common/net".Address, "github.com/v2fly/v2ray-core/v4/common/net".Destination, *"v2ray.com/core/transport/internet".SocketConfig) ("net".Conn, error)

make: *** [build_ios] Error 1

**Comment by Tai7sy** [comment]
See https://github.com/Tai7sy/v2ray_mobile_lib/blob/461556590782631ab961a1049d9a76ca2defe3df/go.mod#L10
only tested in v4.19.1, your version maybe error

**Comment by fuqiangleon** [comment]
yes,  I have fixed it and built it successfully. thank you very much.

**Comment by fuqiangleon** [comment]
yes,  I have fixed it and built it successfully. thank you very much.
